### ISSUE TITLE
add weather icon to bottom right corner

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/sstwickenham#12]

**Comment by dantulloch** [comment]
Core style required to control icons is below:

<div class="detail storm">
                <p class="temp">16&deg;</p>
                <span class="overlay">
                </span>
            </div>

By altering the class on the main div here you can change which weather
icon is shown. The following classes are setup already on the theme:

snow, storm, sun (default - wishful thinking!), rain, snow, overcast
