### ISSUE TITLE
style event links and view more link in calendar - move javascript and CSS from events.php to separate file

### ISSUE THREAD

**Issue by jamiemax** [gemstoneit/sstwickenham#18]

**Comment by dantulloch** [comment]
I can't see the Javascript and CSS on events.php and also there isn't a view more link. Could you elaborate

**Comment by dantulloch** [comment]
Added text underline to links but still not sure where the View More link is

**Comment by dantulloch** [comment]
Whoops - please advise re. the above

**Comment by jamiemax** [comment]
@dantulloch so in order to see that you would need to add more than 4 events to one day, that way the view more link will show

**Comment by dantulloch** [comment]
Completed
